In [22]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/aprendizado-de-mquina-20241-predio-de-churn/sample_submission_.csv
/kaggle/input/aprendizado-de-mquina-20241-predio-de-churn/train_churn_.csv
/kaggle/input/aprendizado-de-mquina-20241-predio-de-churn/test_churn_.csv

In [23]:
df_train = pd.read_csv("/kaggle/input/aprendizado-de-mquina-20241-predio-de-churn/train_churn_.csv", sep=';')
df_test = pd.read_csv("/kaggle/input/aprendizado-de-mquina-20241-predio-de-churn/test_churn_.csv")
sample_submission = pd.read_csv("/kaggle/input/aprendizado-de-mquina-20241-predio-de-churn/sample_submission_.csv")

In [24]:
df_train.head()

,Unnamed: 0,genero,idoso,parceiro,dependentes,tempoDeServico,ServicoTelefone,MultiLinhas,ServicoInternet,ServicoSegurancaCyber,...,StreamingTV,StreamingFilmes,Contrato,BillingDigital,MetodoPagamento,FaturaMensal,FaturaTotal,NumTickets,NumTicketsTecnico,Churn
0,6027,Masculino,0.0,Sim,Sim,35.0,Sim,Sim,Não,Sem serviço de internet,...,Sem serviço de internet,Sem serviço de internet,2 Anos,Não,Transferência Bancária (Automática),25.45,809.25,0.0,0.0,0.0
1,1961,Feminino,0.0,Não,Não,42.0,Sim,Sim,DSL,NaN,...,Não,Não,1 Ano,Sim,Transferência Bancária (Automática),60.15,2421.6,0.0,0.0,0.0
2,5308,Feminino,0.0,Não,Não,69.0,Sim,Não,DSL,Sim,...,Sim,Sim,2 Anos,Sim,Cartão de Crédito (Automático),82.45,5555.3,0.0,0.0,0.0
3,3587,Masculino,1.0,Não,Não,9.0,Sim,NaN,Fibra óptica,Não,...,Sim,Sim,Mensal,Sim,Cartão de Crédito (Automático),99.45,919.4,0.0,0.0,1.0
4,576,Masculino,0.0,Sim,Sim,31.0,Sim,Sim,Fibra óptica,Sim,...,Sim,Não,1 Ano,Não,Transferência Bancária (Automática),98.05,3082.1,NaN,0.0,0.0

In [25]:
# Não embaralhar esses dados de teste.
df_test

,index,Unnamed: 0,genero,idoso,parceiro,dependentes,tempoDeServico,ServicoTelefone,MultiLinhas,ServicoInternet,...,ServicoSuporteTecnico,StreamingTV,StreamingFilmes,Contrato,BillingDigital,MetodoPagamento,FaturaMensal,FaturaTotal,NumTickets,NumTicketsTecnico
0,0,2450,Feminino,0.0,Sim,Sim,72.0,Sim,Sim,Fibra óptica,...,Sim,Sim,Sim,2 Anos,Sim,Transferência Bancária (Automática),110.45,8058.85,0.0,0.0
1,1,4649,Masculino,0.0,Sim,Não,72.0,Sim,Sim,Fibra óptica,...,Sim,Sim,Sim,2 Anos,Sim,Cartão de Crédito (Automático),108.95,NaN,5.0,5.0
2,2,1237,Masculino,0.0,Não,NaN,13.0,Sim,Não,Não,...,Sem serviço de internet,Sem serviço de internet,Sem serviço de internet,1 Ano,Não,Cheque por Carta,19.45,NaN,0.0,0.0
3,3,4415,Masculino,0.0,Sim,NaN,22.0,Sim,NaN,DSL,...,Não,Não,Não,2 Anos,Sim,Cartão de Crédito (Automático),66.10,4428.45,NaN,0.0
4,4,6697,Feminino,0.0,Não,Não,NaN,Sim,Sim,DSL,...,Não,NaN,NaN,1 Ano,Sim,Cartão de Crédito (Automático),79.30,2427.10,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1937,2038,5371,Feminino,0.0,Não,Não,54.0,Sim,Sim,Fibra óptica,...,Não,Sim,Sim,1 Ano,Sim,Transferência Bancária (Automática),103.95,5639.05,0.0,5.0
1938,2039,6974,Feminino,0.0,Sim,Não,51.0,Sim,Sim,Fibra óptica,...,Não,Sim,Sim,1 Ano,Sim,Cheque Eletrônico,98.85,4947.55,0.0,0.0
1939,2040,1908,Masculino,0.0,Não,Não,69.0,Sim,Não,Não,...,Sem serviço de internet,Sem serviço de internet,Sem serviço de internet,2 Anos,Não,Cartão de Crédito (Automático),19.95,1399.35,0.0,0.0
1940,2041,6074,Masculino,0.0,Sim,Não,1.0,Não,Sem serviço de telefone,DSL,...,Não,Não,Não,Mensal,Sim,Cheque Eletrônico,23.45,23.45,0.0,0.0
1941,2042,5588,Masculino,0.0,Não,Não,1.0,Sim,Não,DSL,...,Não,Não,Não,Mensal,Sim,Cheque por Carta,49.65,49.65,0.0,0.0

In [26]:
sample_submission

        ID  Churn
0        0    NaN
1        1    NaN
2        2    NaN
3        3    NaN
4        4    NaN
...    ...    ...
1937  1937    NaN
1938  1938    NaN
1939  1939    NaN
1940  1940    NaN
1941  1941    NaN

[1942 rows x 2 columns]

In [27]:
sample_submission['Churn'] = np.random.choice([1, 0], sample_submission.shape[0]) # A predição de vocês

In [28]:
sample_submission

        ID  Churn
0        0      1
1        1      1
2        2      0
3        3      0
4        4      1
...    ...    ...
1937  1937      0
1938  1938      1
1939  1939      0
1940  1940      0
1941  1941      1

[1942 rows x 2 columns]

In [30]:
sample_submission.to_csv('submission.csv', index = False)